routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');	
});

Route::resource('crud','CrudController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Crud.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Crud extends Model
{
    protected $table = 'crud';
    protected $fillable = ['judul','deskripsi','photo'];
}

app/Http/Controllers/CrudController.php
<?php

namespace App\Http\Controllers;

use App\Models\Crud;
use Illuminate\Http\Request;

class CrudController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title = 'Data Crud';
        $data = Crud::latest()->paginate(5);
  
        return view('crud.index',compact('data','title'))
            ->with('i', (request()->input('page', 1) - 1) * 5);

        // $data = Crud::latest()->get();
        // return view('crud.index', compact('data','title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title = 'Menambahkan data baru';

        return view('crud.create',compact('title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'judul' => 'required',
            'deskripsi' => 'required',
            'photo' => 'required',
        ]);

        $data['judul'] = $request->judul;
        $data['deskripsi'] = $request->deskripsi;
        $data['created_at'] = date('Y-m-d H:i:s');
        $data['updated_at'] = date('Y-m-d H:i:s');

        $file = $request->file('photo');
        if($file){
            $nama_file = rand().'-'. $file->getClientOriginalName();
            $file->move('assets',$nama_file);
            $data['photo'] = 'assets/' .$nama_file;
        }


        Crud::create($data);
        return redirect()->route('crud.index')->with('sukses','Data berhasil diinput');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $title = 'Detail Crud';

        $data=Crud::find($id);
        return view('crud.show',compact('title','data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $title = 'Edit data Crud';

        $data=Crud::find($id);
        return view('crud.edit',compact('title','data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'judul' => 'required',
            'deskripsi' => 'required',
        ]);

        $data['judul'] = $request->judul;
        $data['deskripsi'] = $request->deskripsi;
        $data['updated_at'] = date('Y-m-d H:i:s');

        $file = $request->file('photo');
        if($file){
            $nama_file = rand().'-'. $file->getClientOriginalName();
            $file->move('assets',$nama_file);
            $data['photo'] = 'assets/' .$nama_file;
        }

        Crud::where('id',$id)->update($data);
        return redirect()->route('crud.index')->with('sukses','Data berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data=Crud::find($id);
        $data->delete();
  
        return redirect()->route('crud.index')
                        ->with('sukses','Data berhasil dihapus');
    }
}

resources/views/crud/create.blade.php
@extends('layouts.app')
@section('title')
<title>{{ $title }}</title>
@endsection
@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">{{$title}}</div>

        <div class="card-body">
          @if ($message = Session::get('sukses'))
          <div class="alert alert-success">
            <p>{{ $message }}</p>
          </div>
          @endif
          <form action="{{route('crud.store')}}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="form-group row">
              <label for="inputEmail3" class="col-sm-2 col-form-label">Judul</label>
              <div class="col-sm-10">
                <input type="text" name="judul" class="form-control" id="inputEmail3">
              </div>
            </div>
            <div class="form-group row">
              <label for="inputPassword3" class="col-sm-2 col-form-label">Deskripsi</label>
              <div class="col-sm-10">
                <textarea type="text" name="deskripsi" class="form-control" id="inputPassword3"></textarea>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-2 col-form-label">Upload Photo</label>
              <div class="col-sm-10">
                <input type="file" name="photo" class="form-control-file" id="exampleFormControlFile1">
              </div>
            </div>
            <div class="form-group row">
              <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Simpan</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/crud/edit.blade.php
@extends('layouts.app')
@section('title')
<title>{{ $title }}</title>
@endsection
@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<div class="card">
				<div class="card-header">{{$title}}</div>
				<div class="card-body">
					<form action="{{route('crud.update',$data->id)}}" method="POST" enctype="multipart/form-data">
						{{ csrf_field() }}
						@method('PATCH')
						<div class="form-group row">
							<label for="inputEmail3" class="col-sm-2 col-form-label">Judul</label>
							<div class="col-sm-10">
								<input type="text" name="judul" class="form-control" id="inputEmail3" value="{{$data->judul}}">
							</div>
						</div>
						<div class="form-group row">
							<label for="inputPassword3" class="col-sm-2 col-form-label">Deskripsi</label>
							<div class="col-sm-10">
								<textarea type="text" name="deskripsi" class="form-control" id="inputPassword3">{{$data->deskripsi}}</textarea>
							</div>
						</div>
						<div class="form-group row">
							<label class="col-sm-2 col-form-label">Upload Photo</label>
							<div class="col-sm-10">
								<input type="file" name="photo" class="form-control-file" id="exampleFormControlFile1">
							</div>
						</div>
						<div class="form-group row">
							<div class="col-sm-10">
								<button type="submit" class="btn btn-primary">Simpan</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/crud/index.blade.php
@extends('layouts.app')
@section('title')
<title>{{ $title }}</title>
@endsection
@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<div class="card">
				<div class="card-header">{{$title}}</div>
				<div class="card-body">
					<a href="{{ route('crud.create') }}" class="btn btn-success btn-sm">Tambah Baru</a>
					@if ($message = Session::get('sukses'))
					<div class="alert alert-success">
						<p>{{ $message }}</p>
					</div>
					@endif
					<table class="table">
						<thead class="thead-dark">
							<tr>
								<th scope="col">#</th>
								<th scope="col">Judul</th>
								<th scope="col">Deskripsi</th>
								<th scope="col">Gambar</th>
								<th scope="col">Opsi</th>
							</tr>
						</thead>
						<tbody>
							@foreach($data as $dt)
							<tr>
								<th scope="row">{{ ++$i }}</th>
								<td>{{$dt->judul}}</td>
								<td>{{$dt->deskripsi}}</td>
								<td><img src="{{ asset($dt->photo) }}" style="width: 50px"></td>
								<td>
									<form action="{{ route('crud.destroy',$dt->id) }}" method="POST">
										<a href="{{ route('crud.show',$dt->id) }}" class="btn btn-success btn-sm">Lihat</a>
										<a href="{{ route('crud.edit',$dt->id) }}" class="btn btn-warning btn-sm">Edit</a>
										@csrf
										@method('DELETE')
										<button type="submit" class="btn btn-danger btn-sm">Hapus</button>
									</form>
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/crud/show.blade.php
@extends('layouts.app')
@section('title')
<title>{{ $title }}</title>
@endsection
@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<div class="card">
				<div class="card-header">{{$title}}</div>
				<div class="card-body">
					<table>
						<tr>
							<th>Judul</th>
							<td>: {{$data->judul}}</td>
						</tr>
						<tr>
							<th>Deskripsi</th>
							<td>: {{$data->deskripsi}}</td>
						</tr>
					</table>
					<img src="{{asset($data->photo)}}" style="width: 100px">
				</div>
			</div>
		</div>
	</div>
</div>
@endsection